name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Run Tests
        run: ./mvnw clean test
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
